"""Executive PDF report generation using reportlab."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any, Dict


def build_executive_pdf(prediction_result: Dict[str, Any]) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    except Exception as exc:
        raise RuntimeError('reportlab is required for PDF generation') from exc

    result = prediction_result or {}
    rec = ((result.get('result') or {}).get('recommendation') or {})
    fc = ((result.get('result') or {}).get('final_forecast') or {})
    conf = ((result.get('explainability') or {}).get('confidence_breakdown') or {})

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title='FinSight AI Executive Report')
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph('FinSight AI - Executive Forecast Report', styles['Title']))
    story.append(Paragraph('Confidential', styles['Italic']))
    story.append(Spacer(1, 12))

    story.append(Paragraph('Table of Contents', styles['Heading2']))
    story.append(Paragraph('1. Executive Summary<br/>2. Forecast Overview<br/>3. Agent Breakdown<br/>4. Methodology and Disclaimer', styles['BodyText']))
    story.append(PageBreak())

    story.append(Paragraph('1. Executive Summary', styles['Heading2']))
    story.append(Paragraph(f"Action: {rec.get('action', 'monitor').upper()}", styles['BodyText']))
    story.append(Paragraph(rec.get('simple_summary', 'No summary available.'), styles['BodyText']))
    story.append(Spacer(1, 8))

    story.append(Paragraph('2. Forecast Overview', styles['Heading2']))
    t1 = Table([
        ['Metric', 'P05', 'P50', 'P95'],
        ['Revenue (M USD)', f"{(fc.get('revenue_ci') or [0, 0])[0]:.2f}", f"{fc.get('revenue_p50', 0):.2f}", f"{(fc.get('revenue_ci') or [0, 0])[1]:.2f}"],
        ['EBITDA (M USD)', f"{(fc.get('ebitda_ci') or [0, 0])[0]:.2f}", f"{fc.get('ebitda_p50', 0):.2f}", f"{(fc.get('ebitda_ci') or [0, 0])[1]:.2f}"],
    ])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f766e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
    ]))
    story.append(t1)
    story.append(Spacer(1, 10))

    story.append(Paragraph('3. Agent Breakdown', styles['Heading2']))
    t2 = Table([
        ['Agent', 'Confidence'],
        ['Transcript NLP', f"{(conf.get('transcript_nlp') or 0) * 100:.1f}%"],
        ['Financial Model', f"{(conf.get('financial_model') or 0) * 100:.1f}%"],
        ['News Macro', f"{(conf.get('news_macro') or 0) * 100:.1f}%"],
        ['Competitor', f"{(conf.get('competitor') or 0) * 100:.1f}%"],
    ])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1d4ed8')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(t2)
    story.append(Spacer(1, 10))

    story.append(Paragraph('4. Methodology and Disclaimer', styles['Heading2']))
    story.append(Paragraph('This report is generated by an AI system and should be used for research support only, not as sole investment advice.', styles['BodyText']))

    def _footer(canvas, _doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.drawString(36, 20, f"Generated: {datetime.utcnow().isoformat()}Z")
        canvas.drawRightString(A4[0] - 36, 20, f"Trace: {result.get('trace_id', 'N/A')} | Version: {result.get('model_version', 'N/A')}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
